jikimi/account/urls.py
from django.urls import path
from .views import signup, my_page, uploadProfileImages, UserLoginView
from django.contrib.auth import views as auth_views

app_name = 'account'		# 네임 스페이스

urlpatterns = [
    path("login/", UserLoginView.as_view(template_name = "account/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
    path("my_page/", my_page ,name="mypage"),
    path('upload-prop-images/', uploadProfileImages, name='profile_img'),
]

jikimi/cctv_page/urls.py
from django.urls import path
from .views import cctv_page

app_name = 'cctv_page'		# 네임 스페이스

urlpatterns = [
    path("", cctv_page, name="cctv_page"),
]

jikimi/config/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
	path("",index, name = "index"),
	path("cctv_page/", include('cctv_page.urls')),
    path("account/",include('account.urls')),
    path("violence_data_page/", include('violence_data_page.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

jikimi/violence_data_page/urls.py
from django.urls import path
from .views import violence_data_page

app_name = 'violence_data_page'		# 네임 스페이스

urlpatterns = [
    path("", violence_data_page, name="violence_data_page"),
]

jikimi/templates/nav_bar.html
{% load static %}

<!DOCTYPE html>
  <html lang="ko">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>header</title>
    <link rel="stylesheet" href="{% static 'detail.css' %}">
    <link rel="stylesheet" href="{% static 'navbar_style.css' %}">
    

  </head>
  <body>
    <!--=== header start ===-->
    <nav class="navbar">
      <div class="navbar__logo">
        <a href="{% url 'index' %}" class="logo">JIKIMI</a>
      </div>
      <ul class="navbar__menu">
        <li><a href="{% url 'index' %}">HOME</a></li>
        <li><a href="{% url 'cctv_page:cctv_page' %}">CCTV</a></li>
        <li><a href="{% url 'violence_data_page:violence_data_page' %}">DATA</a></li>

        {% if request.user.is_authenticated %}
          
        <li><a href="{% url 'account:mypage' %}">MY PAGE</a></li>
        <li><a href="{% url 'account:logout' %}">LOGOUT</a></li>
        
        <li>
          <div class="nav-profile-img">
            <img src="/media/{{ request.user.profile_img }}" 
              onerror="this.src='{% static 'my_page/annonymous_user.png' %}'">
          </div>
        </li>

        {% else %}
        
        <li><a href="{% url 'account:login' %}">LOGIN</a></li>
        <li><a href="{% url 'account:signup' %}">SIGNUP</a></li>        
        
        {% endif %}
     
      </ul>
      <a href="#" class="navbar__toggleBtn"> <i class="fas fa-bars"></i> </a>
	</nav>

  </body>
  
  <script>
  
	const toggleBtn = document.querySelector('.navbar__toggleBtn');
	const menu = document.querySelector('.navbar__menu');


	toggleBtn.addEventListener('click', () => {
        menu.classList.toggle('active');
        // sns.classList.toggle('active');
	});
  </script>
  
  
  </html>

jikimi/templates/nav_bar_bak.html
{% load static %}

<!DOCTYPE html>
  <html lang="ko">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>header</title>
    <link rel="stylesheet" href="{% static 'detail.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    

  </head>
  <body>
    <!--=== header start ===-->
  <header>
    <a href="{% url 'index' %}" class="logo">JIKIMI</a>
    <nav class="navbar">
      <a href="#" class="navbar__toggleBtn"> <i class="fas fa-bars"></i> </a>
      
      <ul class="navbar__menu">
        <li><a href="{% url 'index' %}">HOME</a></li>
        <li><a href="{% url 'cctv_page:cctv_page' %}">CCTV</a></li>
        <li><a href="{% url 'violence_data_page:violence_data_page' %}">DATA</a></li>

        {% if request.user.is_authenticated %}
          
        <li><a href="{% url 'account:mypage' %}">MY PAGE</a></li>
        <li><a href="{% url 'account:logout' %}">LOGOUT</a></li>
        
        <li>
          <div class="nav-profile-img" style="margin-top: 0.7rem;">
            <img src="/media/{{ request.user.profile_img }}" 
              onerror="this.src='{% static 'my_page/annonymous_user.png' %}'" id="pf_nav_img">
          </div>
        </li>

        {% else %}
        
        <li><a href="{% url 'account:login' %}">LOGIN</a></li>
        <li><a href="{% url 'account:signup' %}">SIGNUP</a></li>        
        
        {% endif %}
      
      </ul>
	  
    </nav>
  </header>
  </body>
  
  <script>
  
	const toggleBtn = document.querySelector('.navbar__toggleBtn');
	const menu = document.querySelector('.navbar__menu');
	const sns = document.querySelector('.navbar__sns');

	toggleBtn.addEventListener('click', () => {
        menu.classList.toggle('active');
        // sns.classList.toggle('active');
	});
  </script>
  
  
  </html>

jikimi/templates/parent_page.html
{% load static %}
<!DOCTYPE HTML>

<html>

	<head>
	
		<meta charset='utf-8'>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- 반응형 웹페이지를 만들 때 반드시 기입해야함! -->

		<!-- <link rel="stylesheet" type = "text/css" href = "{% static 'bootstrap.min.css' %}"> -->
		<link rel="stylesheet" type = "text/css" href = "{% static 'main_page.css' %}">
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css">
	
		<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script> 
		
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
		<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
		<script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
		
	</head>
		 
	<body>
			{% include "nav_bar.html" %}
			
			{% block content %} {% endblock %}
	</body>


</html>